# Just commands for common dev tasks

set shell := ["bash", "-cu"]

# Start PostgreSQL container
up:
	docker compose up -d db

# Stop PostgreSQL container
stop:
	docker compose stop db

# Run backend (FastAPI)
backend:
	cd backend && poetry run uvicorn app.main:app --reload

# Run frontend (React)
frontend:
	cd frontend && if [ ! -d node_modules ]; then npm install; fi && npm run dev

# Install backend Python dependencies with Poetry
install-deps:
	cd backend && poetry install

# Run latest migrations
migrate:
	cd backend && poetry run alembic upgrade head

# Create a new autogenerated migration with a message
migration msg:
	cd backend && poetry run alembic revision --autogenerate -m "{{msg}}"

# Downgrade database to a specific revision
downgrade rev:
	cd backend && poetry run alembic downgrade {{rev}}

# Danger: stop & remove ALL Docker containers and prune unused resources
wipe-docker:
	if [ -n "$(docker ps -aq)" ]; then docker stop $(docker ps -aq) || true; fi
	if [ -n "$(docker ps -aq)" ]; then docker rm $(docker ps -aq) || true; fi
	docker volume prune -f || true
	docker network prune -f || true
	docker system prune -f || true

# Danger: drop and recreate the public schema in the inventory database
drop-tables:
	docker compose exec -T db psql -U inventory_user -d inventory -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"

# Danger: delete all Alembic version files and create a new autogenerated base migration
new-base-migration:
	rm -f backend/alembic/versions/*.py
	cd backend && ALEMBIC_IGNORE_DB_STATE=1 poetry run alembic revision --autogenerate -m "base"

# Seed database with demo suppliers, products, and stock movements
seed:
	cd backend && poetry run python -m app.seed_demo_data
